# Generated by Django 5.1.3 on 2024-11-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0004_alter_game_buyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
